# Generated by Django 6.0.3 on 2026-03-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='search_placeholders',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for the storefront search bar, e.g. ["dal","rice"].'),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('portal_main', 'Customer portal'), ('portal_family', 'Family portal'), ('portal_child', 'Child portal')], db_index=True, max_length=20)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(help_text='Lucide icon export name, e.g. Home, Wallet', max_length=80)),
                ('parent_key', models.CharField(blank=True, default='', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('badge_key', models.CharField(blank=True, help_text='Resolved server-side to a count when applicable (e.g. pending_orders).', max_length=80)),
                ('roles_filter', models.CharField(blank=True, help_text='Comma-separated User.role values (portal surfaces only); empty = visible to all.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Navigation items',
                'ordering': ['surface', 'parent_key', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('surface', 'key'), name='uniq_navigation_surface_key')],
            },
        ),
    ]
