# Generated by Django 6.0.3 on 2026-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='cms/'),
        ),
    ]
