# Generated by Django 6.0.3 on 2026-04-03 16:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cmspage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_addresses', to='core.shippingzone'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='default_checkout_weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Used for storefront quotes when cart has no per-product weights.', max_digits=8),
        ),
    ]
