# Generated by Django 6.0.3 on 2026-04-05 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_completed_to_approved(apps, schema_editor):
    WalletWithdrawal = apps.get_model("core", "WalletWithdrawal")
    WalletWithdrawal.objects.filter(status="completed").update(status="approved")


def backwards_approved_to_completed(apps, schema_editor):
    WalletWithdrawal = apps.get_model("core", "WalletWithdrawal")
    WalletWithdrawal.objects.filter(status="approved").update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_shipping_checkout_social_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletwithdrawal",
            name="reject_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="walletwithdrawal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            forwards_completed_to_approved,
            backwards_approved_to_completed,
        ),
        migrations.AlterField(
            model_name="walletwithdrawal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("esewa", "eSewa"),
                            ("khalti", "Khalti"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(blank=True, upload_to="payout_qr/"),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "bank_account_holder",
                    models.CharField(blank=True, max_length=150),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="walletwithdrawal",
            name="payout_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawals",
                to="core.payoutaccount",
            ),
        ),
    ]
