# Generated by Django 6.0.3 on 2026-03-24 20:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_customer_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_currency_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Points earned per 1.00 currency unit spent (e.g. 0.01 = 1 pt per Rs.100).', max_digits=12)),
                ('redeem_points_per_currency', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), help_text='Points required to redeem 1.00 currency unit as wallet credit.', max_digits=12)),
                ('min_redeem_points', models.PositiveIntegerField(default=100)),
                ('max_redeem_per_order', models.PositiveIntegerField(default=50000)),
                ('referral_bonus_points', models.PositiveIntegerField(default=50)),
                ('loyalty_program_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_sensitive_crud', models.BooleanField(default=True)),
                ('rbac_enforced', models.BooleanField(default=True)),
                ('duplicate_prevention', models.BooleanField(default=True)),
                ('auto_lock_failed_logins', models.BooleanField(default=True)),
                ('ip_rate_limiting', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Security settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_pays_shipping', models.BooleanField(default=False)),
                ('free_shipping_global', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.shippingzone')),
            ],
            options={
                'verbose_name_plural': 'Shipping settings',
            },
        ),
    ]
