# Generated by Django 6.0.3 on 2026-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loyalty_security_shipping_settings_and_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='document_file',
            field=models.FileField(blank=True, upload_to='kyc/files/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_image',
            field=models.ImageField(blank=True, upload_to='kyc/'),
        ),
    ]
