# Generated by Django 6.0.3 on 2026-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kyc_document_file_optional_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_validity_days', models.PositiveIntegerField(default=7)),
                ('auto_cancel_hours', models.PositiveIntegerField(default=48)),
                ('guest_checkout', models.BooleanField(default=True)),
                ('order_verification_required', models.BooleanField(default=True)),
                ('auto_assign_delivery', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Order settings',
            },
        ),
    ]
