# Generated by Django 6.0.3 on 2026-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_extras',
            field=models.JSONField(blank=True, default=dict, help_text='Nested settings for admin tabs (analytics, appearance, email, etc.).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kyc_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pos_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
