# Generated by Django 6.0.3 on 2026-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_discount_type_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='net_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='platform_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('topup', 'Top-up'), ('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('commission_in', 'Commission in'), ('vendor_settlement', 'Vendor settlement'), ('refund_vendor_dbt', 'Refund vendor clawback'), ('refund_plat_dbt', 'Refund platform clawback'), ('refund_plat_fee', 'Refund platform fee retained'), ('refund_credit', 'Refund to customer')], max_length=20),
        ),
    ]
