# Generated by Django 6.0.3 on 2026-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_site_settings_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='signup_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
