# Generated by Django 6.0.3 on 2026-04-08 16:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_refund_platform_fee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='If non-empty, coupon applies only to these products (and vendor/category rules).', related_name='coupon_targets', to='core.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="This line's share of order-level coupon discount.", max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flash_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.flashdeal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='list_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product list price at checkout (before product-level sale).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Line total after coupon: unit_price × quantity − coupon_discount_amount.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price after flash (and product sale); before coupon allocation.', max_digits=10),
        ),
    ]
