# Generated by Django 6.0.3 on 2026-04-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_smtp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='Must be the authenticated mailbox or a verified Send mail as alias for that account. Overridable via KP_SMTP_FROM_EMAIL.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_from_name',
            field=models.CharField(blank=True, help_text='Display name for the From header. Overridable via KP_SMTP_FROM_NAME.', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server hostname. Gmail: smtp.gmail.com. Alternatives: SendGrid, SES, Resend, Mailgun SMTP hosts.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Gmail/Google: use an App Password (2-Step Verification required), not your normal password. Prefer KP_SMTP_PASSWORD in server environment for production.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, help_text='587 with TLS (default) or 465 with SSL. Overridable via KP_SMTP_PORT.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='SMTP login user. Gmail: full Google account email. Overridable via KP_SMTP_USERNAME.', max_length=255),
        ),
    ]
