# Generated by Django 6.0.3 on 2026-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_smtp_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('transfer', 'Transfer'), ('withdraw', 'Withdraw'), ('freeze', 'Freeze'), ('family_invite', 'Family invite'), ('admin_sensitive', 'Admin sensitive')], max_length=20),
        ),
    ]
