# Generated by Django 6.0.3 on 2026-04-08 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_otp_admin_sensitive_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletsettings',
            name='cross_portal_transfer_by_code_enabled',
            field=models.BooleanField(default=False, help_text='Allow wallet-hub transfers by transfer code across portals (parent/child/personal rules apply).'),
        ),
        migrations.CreateModel(
            name='WalletTransferCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('qr_image', models.ImageField(blank=True, upload_to='wallet_transfer_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfer_code_row', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet transfer code',
                'verbose_name_plural': 'Wallet transfer codes',
            },
        ),
        migrations.CreateModel(
            name='WalletTransferIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('outbound_txn_id', models.CharField(blank=True, max_length=30)),
                ('cached_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_hub_idempotency_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sender', 'client_key'), name='wallet_hub_idem_sender_client_key')],
            },
        ),
    ]
