# Generated by Django 6.0.3 on 2026-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reel_boost_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_cover',
            field=models.ImageField(blank=True, upload_to='customers/covers/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.TextField(blank=True),
        ),
    ]
