# Generated by Django 6.0.3 on 2026-04-11 09:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplier_code', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('sale_settlement', 'Sale settlement'), ('sale_reversal', 'Sale reversal'), ('purchase_cost', 'Stock purchase'), ('adjustment', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive credits vendor book, negative is cost/outflow.', max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.vendor')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_ledger_entries', to='core.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorStockPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_purchases', to='core.supplier')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_purchases', to='core.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorStockPurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.vendorstockpurchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_code__gt', '')), fields=('vendor', 'supplier_code'), name='supplier_unique_code_per_vendor'),
        ),
        migrations.AddIndex(
            model_name='vendorledgerentry',
            index=models.Index(fields=['vendor', '-created_at'], name='core_vendor_vendor__4cf6bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'sale_settlement'), ('reference_type', 'Order'), models.Q(('reference_id', ''), _negated=True)), fields=('vendor', 'entry_type', 'reference_type', 'reference_id'), name='uniq_vendor_ledger_sale_settlement_order'),
        ),
        migrations.AddConstraint(
            model_name='vendorledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'sale_reversal'), ('reference_type', 'Order'), models.Q(('reference_id', ''), _negated=True)), fields=('vendor', 'entry_type', 'reference_type', 'reference_id'), name='uniq_vendor_ledger_sale_reversal_order'),
        ),
        migrations.AddConstraint(
            model_name='vendorledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'purchase_cost'), ('reference_type', 'VendorStockPurchase'), models.Q(('reference_id', ''), _negated=True)), fields=('vendor', 'entry_type', 'reference_type', 'reference_id'), name='uniq_vendor_ledger_purchase_doc'),
        ),
    ]
