# Generated by Django 6.0.3 on 2026-03-28 05:59

import core.models
import django.db.models.deletion
from decimal import Decimal

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def _backfill_category_roles_and_seed_hubs(apps, schema_editor):
    FamilyWalletCategory = apps.get_model("core", "FamilyWalletCategory")
    User = apps.get_model("core", "User")
    FamilyGroup = apps.get_model("core", "FamilyGroup")
    FamilyGroupPermission = apps.get_model("core", "FamilyGroupPermission")
    Wallet = apps.get_model("core", "Wallet")

    for cat in FamilyWalletCategory.objects.all():
        roles = cat.allowed_member_roles
        if roles is None or roles == []:
            cat.allowed_member_roles = ["child"]
            cat.save(update_fields=["allowed_member_roles"])

    hub_phone = "9800000000"
    leader = User.objects.filter(phone=hub_phone).first()
    if not leader:
        leader = User(
            phone=hub_phone,
            name="Platform Hub System",
            username="platform_hub_system",
            email="",
            role="parent",
            is_active=True,
            is_staff=False,
            is_superuser=False,
        )
        leader.password = make_password(None)
        leader.save()

    hub_defs = [
        ("flat", "Platform shared flat"),
        ("hotel", "Platform shared hotel"),
        ("hostel", "Platform shared hostel"),
    ]
    for gtype, gname in hub_defs:
        if FamilyGroup.objects.filter(is_platform_hub=True, type=gtype).exists():
            continue
        group = FamilyGroup.objects.create(
            name=gname,
            leader_id=leader.pk,
            type=gtype,
            status="active",
            is_platform_hub=True,
        )
        FamilyGroupPermission.objects.get_or_create(group_id=group.pk)
        Wallet.objects.create(
            owner_id=leader.pk,
            type="shared",
            label="Family wallet",
            family_group_id=group.pk,
            status="active",
            balance=Decimal("0.00"),
            currency="NPR",
        )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_default_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='is_platform_hub',
            field=models.BooleanField(db_index=True, default=False, help_text='Singleton group shared by all users of this type (flat/hotel/hostel).'),
        ),
        migrations.AddField(
            model_name='familywalletcategory',
            name='allowed_member_roles',
            field=models.JSONField(default=core.models._default_wallet_category_roles, help_text='FamilyMember.role values allowed for distribution/transfers, e.g. ["child"].'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='family_wallet_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='core.familywalletcategory'),
        ),
        migrations.RunPython(_backfill_category_roles_and_seed_hubs, _noop_reverse),
    ]
