# Generated by Django 6.0.3 on 2026-03-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_family_portal_hub_wallet_category_txn'),
    ]

    operations = [
        migrations.AddField(
            model_name='familywalletcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='family_wallet_categories/'),
        ),
    ]
