# Generated by Django 6.0.3 on 2026-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_navigationitem_view_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygrouppermission',
            name='default_invite_spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default monthly spending limit for batch member invites (family portal).', max_digits=10, null=True),
        ),
    ]
