# Generated by Django 6.0.4 on 2026-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_support_ticket_reader_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('oauth_phone', 'OAuth phone'), ('transfer', 'Transfer'), ('withdraw', 'Withdraw'), ('freeze', 'Freeze'), ('family_invite', 'Family invite'), ('admin_sensitive', 'Admin sensitive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_avatar_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
    ]
