# Generated by Django 6.0.3 on 2026-03-28 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_family_group_default_invite_spending_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyjoinrequest',
            name='applicant_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familyjoinrequest',
            name='source',
            field=models.CharField(choices=[('parent_invite', 'Parent invite'), ('share_link', 'Share link')], default='parent_invite', max_length=20),
        ),
        migrations.AlterField(
            model_name='familyjoinrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_join_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FamilyPortalJoinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('default_role', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('guest', 'Guest'), ('manager', 'Manager')], default='child', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Short heading shown on the public join page.', max_length=120)),
                ('welcome_message', models.TextField(blank=True, help_text='Optional message shown to applicants.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, link stops accepting applications after this time.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_portal_join_links_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_join_links', to='core.familygroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='familyjoinrequest',
            name='join_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='core.familyportaljoinlink'),
        ),
    ]
