# Generated by Django 6.0.4 on 2026-04-18 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_otpverification_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='refund_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Percentage of the proportional commission slice retained by the platform on refunds (0–100).', max_digits=5),
        ),
    ]
