# Generated by Django 6.0.3 on 2026-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_purchase_order_lines_and_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
    ]
