# Generated by Django 6.0.3 on 2026-03-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_site_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdeal',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_flash_deals', to='core.vendor'),
        ),
    ]
