# Generated by Django 6.0.3 on 2026-03-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_kycdocument_document_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_kind',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('read', 'Read'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
