# Generated by Django 6.0.3 on 2026-03-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auditlog_action_kind_module_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('parent', 'Parent'), ('child', 'Child'), ('vendor', 'Vendor'), ('shared', 'Shared'), ('platform', 'Platform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer'), ('topup', 'Top-up'), ('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('commission_in', 'Commission in'), ('vendor_settlement', 'Vendor settlement')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'platform')), fields=('type',), name='wallet_unique_platform_type'),
        ),
        migrations.AddField(
            model_name='ordercommissionsettlement',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_settlement', to='core.order'),
        ),
        migrations.AddField(
            model_name='ordercommissionsettlement',
            name='platform_wallet_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlement_platform', to='core.wallettransaction'),
        ),
        migrations.AddField(
            model_name='ordercommissionsettlement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='ordercommissionsettlement',
            name='vendor_wallet_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlement_vendor', to='core.wallettransaction'),
        ),
    ]
