# Generated by Django 6.0.3 on 2026-03-29 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_support_tickets(apps, schema_editor):
    SupportTicket = apps.get_model("core", "SupportTicket")
    SupportTicketMessage = apps.get_model("core", "SupportTicketMessage")
    Vendor = apps.get_model("core", "Vendor")
    vendor_user_ids = set(Vendor.objects.values_list("user_id", flat=True))
    for t in SupportTicket.objects.all().iterator():
        updates = []
        if t.submitter_id in vendor_user_ids and t.source_panel == "customer":
            t.source_panel = "vendor"
            updates.append("source_panel")
        if t.last_activity_at is None:
            t.last_activity_at = t.created_at
            updates.append("last_activity_at")
        if updates:
            t.save(update_fields=updates)
        if not SupportTicketMessage.objects.filter(ticket_id=t.pk).exists():
            SupportTicketMessage.objects.create(
                ticket_id=t.pk,
                sender_id=t.submitter_id,
                body=(t.description or "")[:10000],
            )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_wallettransaction_fund_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-last_activity_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('billing', 'Billing'), ('account', 'Account'), ('orders', 'Orders'), ('wallet', 'Wallet'), ('technical', 'Technical'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='source_panel',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('family', 'Family'), ('child', 'Child')], db_index=True, default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('wallet', 'Wallet'), ('kyc', 'KYC'), ('family', 'Family'), ('stock', 'Stock'), ('marketing', 'Marketing'), ('security', 'Security'), ('system', 'System'), ('support', 'Support')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='core_suppor_ticket__f4c593_idx')],
            },
        ),
        migrations.RunPython(_backfill_support_tickets, _noop_reverse),
    ]
