# Generated by Django 6.0.4 on 2026-05-27 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sitesettings_seo_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('nchl_qr', 'NCHL QR')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txn_ref', models.CharField(max_length=100, unique=True)),
                ('cart_payload', models.JSONField(blank=True, default=dict)),
                ('qr_payload', models.TextField(blank=True, help_text='Base64 data URL or image URL for dynamic QR display.')),
                ('qr_string', models.TextField(blank=True, help_text='EMVCo / payload string for client-side QR rendering.')),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='userfcmdevice',
            new_name='core_userfc_user_id_63115e_idx',
            old_name='core_userfc_user_id_updated_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('ime_pay', 'IME Pay'), ('wallet', 'Wallet'), ('cash', 'Cash'), ('card', 'Card'), ('nchl_qr', 'NCHL QR')], max_length=20),
        ),
        migrations.AddField(
            model_name='pospaymentsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_payment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pospaymentsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_payment_sessions', to='core.order'),
        ),
        migrations.AddField(
            model_name='pospaymentsession',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sessions', to='core.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='pospaymentsession',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_payment_sessions', to='core.vendor'),
        ),
    ]
