# Generated by Django 6.0.3 on 2026-03-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_support_ticket_chat_and_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_tickets/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportticketmessage')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['message', 'id'], name='core_suppor_message_07b21e_idx')],
            },
        ),
    ]
