# Generated by Django 6.0.3 on 2026-03-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_support_ticket_message_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='banner',
            name='card_variant',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='banner',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('category', 'Category'), ('sidebar', 'Sidebar'), ('promo_strip', 'Home promo strip')], max_length=20),
        ),
    ]
