# Generated by Django 6.0.3 on 2026-03-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_banner_promo_strip_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="placement",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("category", "Category"),
                    ("sidebar", "Sidebar"),
                    ("promo_strip", "Home promo strip"),
                    ("small_strip", "Small strip"),
                    ("footer_promo", "Footer promo"),
                ],
                max_length=20,
            ),
        ),
    ]
