from django.urls import path

from core.views.admin import (
    admin_vendor_inventory_views,
    dashboard_views,
    kyc_submissions_views,
    resource_views,
    system_cleanup_views,
    user_views,
)
from core.views import navigation_views

urlpatterns = [
    path("navigation/", navigation_views.admin_navigation, name="admin-navigation"),
    path("auth/login/", user_views.admin_login, name="admin-login"),
    path("auth/logout/", user_views.admin_logout, name="admin-logout"),
    path("auth/change-password/", user_views.admin_change_password, name="admin-change-password"),
    path("profile/", user_views.admin_self_profile, name="admin-self-profile"),
    path(
        "me/notifications/mark-read/",
        resource_views.admin_me_notifications_mark_read,
        name="admin-me-notifications-mark-read",
    ),
    path(
        "me/notifications/",
        resource_views.admin_me_notifications_list,
        name="admin-me-notifications",
    ),
    path("users/", user_views.users_list, name="admin-users"),
    path("users/create/", user_views.admin_user_create, name="admin-users-create"),
    path(
        "users/<int:pk>/kyc-documents/",
        user_views.admin_user_kyc_documents,
        name="admin-users-kyc-documents",
    ),
    path(
        "kyc-submissions/<int:pk>/",
        kyc_submissions_views.admin_kyc_submission_write,
        name="admin-kyc-submissions-write",
    ),
    path(
        "kyc-submissions/",
        kyc_submissions_views.admin_kyc_submissions_list,
        name="admin-kyc-submissions-list",
    ),
    path("users/<int:pk>/", user_views.admin_user_detail_write, name="admin-users-write"),
    path("users/staff/", resource_views.admin_staff_users_list, name="admin-users-staff"),
    path("dashboard/summary/", dashboard_views.dashboard_summary, name="admin-dashboard-summary"),
    path("dashboard/recent-orders/", dashboard_views.dashboard_recent_orders, name="admin-dashboard-recent-orders"),
    path("dashboard/sales-series/", dashboard_views.dashboard_sales_series, name="admin-dashboard-sales-series"),
    path(
        "dashboard/wallet-series/",
        dashboard_views.dashboard_wallet_series,
        name="admin-dashboard-wallet-series",
    ),
    path(
        "dashboard/low-stock/",
        dashboard_views.dashboard_low_stock,
        name="admin-dashboard-low-stock",
    ),
    path("dashboard/reports/", dashboard_views.dashboard_reports, name="admin-dashboard-reports"),
    path("orders/", resource_views.admin_orders_list, name="admin-orders"),
    path("order-settings/", resource_views.admin_order_settings_singleton, name="admin-order-settings"),
    path(
        "orders/<int:pk>/refund/",
        resource_views.admin_order_refund,
        name="admin-order-refund",
    ),
    path("orders/<int:pk>/", resource_views.admin_order_detail, name="admin-order-detail"),
    path("products/", resource_views.admin_products_list, name="admin-products"),
    path("products/create/", resource_views.admin_product_create, name="admin-products-create"),
    path("products/<int:pk>/", resource_views.admin_product_detail_write, name="admin-products-write"),
    path("vendors/create/", resource_views.admin_vendor_create, name="admin-vendors-create"),
    path(
        "vendors/all/suppliers/",
        admin_vendor_inventory_views.admin_suppliers_all,
        name="admin-suppliers-all",
    ),
    path(
        "vendors/all/stock-purchases/",
        admin_vendor_inventory_views.admin_stock_purchases_all,
        name="admin-stock-purchases-all",
    ),
    path(
        "vendors/all/ledger/",
        admin_vendor_inventory_views.admin_vendor_ledger_all,
        name="admin-vendor-ledger-all",
    ),
    path(
        "vendors/<int:vendor_pk>/suppliers/<int:sp_pk>/ledger/",
        admin_vendor_inventory_views.admin_vendor_supplier_ledger,
        name="admin-vendor-supplier-ledger",
    ),
    path(
        "vendors/<int:vendor_pk>/suppliers/<int:pk>/",
        admin_vendor_inventory_views.admin_vendor_supplier_detail,
        name="admin-vendor-supplier-detail",
    ),
    path(
        "vendors/<int:vendor_pk>/suppliers/",
        admin_vendor_inventory_views.admin_vendor_suppliers,
        name="admin-vendor-suppliers",
    ),
    path(
        "vendors/<int:vendor_pk>/ledger/",
        admin_vendor_inventory_views.admin_vendor_ledger,
        name="admin-vendor-ledger",
    ),
    path(
        "vendors/<int:vendor_pk>/stock-purchases/<int:pk>/",
        admin_vendor_inventory_views.admin_vendor_stock_purchase_detail,
        name="admin-vendor-stock-purchase-detail",
    ),
    path(
        "vendors/<int:vendor_pk>/stock-purchases/<int:pk>/post/",
        admin_vendor_inventory_views.admin_vendor_stock_purchase_post,
        name="admin-vendor-stock-purchase-post",
    ),
    path(
        "vendors/<int:vendor_pk>/stock-purchases/",
        admin_vendor_inventory_views.admin_vendor_stock_purchases,
        name="admin-vendor-stock-purchases",
    ),
    path(
        "vendors/<int:pk>/impersonate/",
        resource_views.admin_vendor_impersonate,
        name="admin-vendors-impersonate",
    ),
    path("vendors/<int:pk>/", resource_views.admin_vendor_detail_write, name="admin-vendors-write"),
    path("vendors/", resource_views.admin_vendors_list, name="admin-vendors"),
    path("reels/create/", resource_views.admin_reel_create, name="admin-reels-create"),
    path("reels/<int:pk>/", resource_views.admin_reel_detail_write, name="admin-reels-write"),
    path("reels/", resource_views.admin_reels_list, name="admin-reels"),
    path("categories/", resource_views.admin_categories_flat, name="admin-categories"),
    path("categories/create/", resource_views.admin_category_create, name="admin-categories-create"),
    path("categories/<int:pk>/", resource_views.admin_category_detail_write, name="admin-categories-write"),
    path("brands/", resource_views.admin_brands_list, name="admin-brands"),
    path("brands/create/", resource_views.admin_brand_create, name="admin-brands-create"),
    path("brands/<int:pk>/", resource_views.admin_brand_detail_write, name="admin-brands-write"),
    path("attributes/", resource_views.admin_attributes_list, name="admin-attributes"),
    path("attributes/create/", resource_views.admin_attribute_create, name="admin-attributes-create"),
    path("attributes/<int:pk>/", resource_views.admin_attribute_detail_write, name="admin-attributes-write"),
    path("attribute-values/", resource_views.admin_attribute_values_list, name="admin-attribute-values"),
    path("attribute-values/create/", resource_views.admin_attribute_value_create, name="admin-attribute-values-create"),
    path("attribute-values/<int:pk>/", resource_views.admin_attribute_value_detail_write, name="admin-attribute-values-write"),
    path("units/", resource_views.admin_units_list, name="admin-units"),
    path("units/create/", resource_views.admin_unit_create, name="admin-units-create"),
    path("units/<int:pk>/", resource_views.admin_unit_detail_write, name="admin-units-write"),
    path("reviews/", resource_views.admin_reviews_list, name="admin-reviews"),
    path("reviews/<int:pk>/", resource_views.admin_review_detail_write, name="admin-reviews-write"),
    path("product-approvals/", resource_views.admin_product_approvals_list, name="admin-product-approvals"),
    path(
        "product-approvals/<int:pk>/",
        resource_views.admin_product_approval_write,
        name="admin-product-approvals-write",
    ),
    path("coupons/create/", resource_views.admin_coupon_create, name="admin-coupons-create"),
    path("coupons/<int:pk>/", resource_views.admin_coupon_detail_write, name="admin-coupons-write"),
    path("coupons/", resource_views.admin_coupons_list, name="admin-coupons"),
    path("flash-deals/create/", resource_views.admin_flash_deal_create, name="admin-flash-deals-create"),
    path("flash-deals/<int:pk>/", resource_views.admin_flash_deal_detail_write, name="admin-flash-deals-write"),
    path("flash-deals/", resource_views.admin_flash_deals_list, name="admin-flash-deals"),
    path("banners/", resource_views.admin_banners_list, name="admin-banners"),
    path("banners/create/", resource_views.admin_banner_create, name="admin-banners-create"),
    path("banners/<int:pk>/", resource_views.admin_banner_detail_write, name="admin-banners-write"),
    path("cms-pages/", resource_views.admin_cms_pages_list, name="admin-cms-pages"),
    path("cms-pages/create/", resource_views.admin_cms_page_create, name="admin-cms-pages-create"),
    path("cms-pages/<int:pk>/", resource_views.admin_cms_page_detail_write, name="admin-cms-pages-write"),
    path(
        "notifications/broadcast/",
        resource_views.admin_notification_broadcast,
        name="admin-notifications-broadcast",
    ),
    path("notifications/<int:pk>/", resource_views.admin_notification_detail_write, name="admin-notifications-write"),
    path("notifications/", resource_views.admin_notifications_list, name="admin-notifications"),
    path(
        "refunds/<str:refund_number>/",
        resource_views.admin_refund_detail_write,
        name="admin-refunds-write",
    ),
    path("refunds/", resource_views.admin_refunds_list, name="admin-refunds"),
    path("payments/", resource_views.admin_payments_list, name="admin-payments"),
    path("ledger-transactions/", resource_views.admin_ledger_transactions_list, name="admin-ledger-transactions"),
    path(
        "commission-settlements/",
        resource_views.admin_commission_settlements_list,
        name="admin-commission-settlements",
    ),
    path("withdrawals/", resource_views.admin_withdrawals_list, name="admin-withdrawals"),
    path(
        "withdrawals/summary/",
        resource_views.admin_withdrawals_summary,
        name="admin-withdrawals-summary",
    ),
    path("withdrawals/<int:pk>/", resource_views.admin_withdrawal_detail_write, name="admin-withdrawals-write"),
    path(
        "payout-accounts/",
        resource_views.admin_payout_accounts_list,
        name="admin-payout-accounts",
    ),
    path("wallets/summary/", resource_views.admin_wallets_summary, name="admin-wallets-summary"),
    path("wallets/adjust/", resource_views.admin_wallet_adjust, name="admin-wallets-adjust"),
    path("wallets/<int:pk>/", resource_views.admin_wallet_detail_write, name="admin-wallets-write"),
    path("wallets/", resource_views.admin_wallets_list, name="admin-wallets"),
    path("wallet/topup/", dashboard_views.admin_wallet_topup, name="admin-wallet-topup"),
    path(
        "wallet/topup/khalti/verify/",
        dashboard_views.admin_wallet_topup_khalti_verify,
        name="admin-wallet-topup-khalti-verify",
    ),
    path("wallet-settings/", resource_views.admin_wallet_settings_singleton, name="admin-wallet-settings"),
    path("wallet-transactions/", resource_views.admin_wallet_transactions_list, name="admin-wallet-txns"),
    path("wallet-bonuses/create/", resource_views.admin_wallet_bonus_create, name="admin-wallet-bonuses-create"),
    path("wallet-bonuses/<int:pk>/", resource_views.admin_wallet_bonus_detail_write, name="admin-wallet-bonuses-write"),
    path("wallet-bonuses/", resource_views.admin_wallet_bonuses_list, name="admin-wallet-bonuses"),
    path("loyalty-rules/create/", resource_views.admin_loyalty_rule_create, name="admin-loyalty-rules-create"),
    path("loyalty-rules/<int:pk>/", resource_views.admin_loyalty_rule_detail_write, name="admin-loyalty-rules-write"),
    path("loyalty-rules/", resource_views.admin_loyalty_rules_list, name="admin-loyalty-rules"),
    path("loyalty-settings/", resource_views.admin_loyalty_settings_singleton, name="admin-loyalty-settings"),
    path("loyalty/summary/", resource_views.admin_loyalty_summary, name="admin-loyalty-summary"),
    path("families/create/", resource_views.admin_family_create, name="admin-families-create"),
    path("families/<int:pk>/members/", resource_views.admin_family_members_list, name="admin-family-members"),
    path(
        "families/<int:pk>/members/add/",
        resource_views.admin_family_member_create,
        name="admin-family-members-create",
    ),
    path(
        "families/<int:pk>/permissions/",
        resource_views.admin_family_permissions_write,
        name="admin-family-permissions",
    ),
    path("families/<int:pk>/", resource_views.admin_family_detail_write, name="admin-families-write"),
    path("family-members/<int:pk>/", resource_views.admin_family_member_detail_write, name="admin-family-member-write"),
    path("families/", resource_views.admin_families_list, name="admin-families"),
    path("purchase-orders/", resource_views.admin_purchase_orders_list, name="admin-purchase-orders"),
    path("pos/checkout/", resource_views.admin_pos_checkout, name="admin-pos-checkout"),
    path("purchase-orders/create/", resource_views.admin_purchase_order_create, name="admin-purchase-orders-create"),
    path(
        "purchase-orders/pos-orders/<int:pk>/",
        resource_views.admin_pos_order_billing_detail,
        name="admin-pos-order-billing-detail",
    ),
    path(
        "purchase-orders/<int:pk>/",
        resource_views.admin_purchase_order_detail,
        name="admin-purchase-order-detail",
    ),
    path("delivery-men/create/", resource_views.admin_delivery_man_create, name="admin-delivery-men-create"),
    path("delivery-men/<int:pk>/", resource_views.admin_delivery_man_detail_write, name="admin-delivery-men-write"),
    path("delivery-men/", resource_views.admin_delivery_men_list, name="admin-delivery-men"),
    path(
        "audit-logs/filter-options/",
        resource_views.admin_audit_log_filter_options,
        name="admin-audit-log-filter-options",
    ),
    path(
        "audit-logs/<int:pk>/",
        resource_views.admin_audit_log_detail,
        name="admin-audit-log-detail",
    ),
    path("audit-logs/", resource_views.admin_audit_logs_list, name="admin-audit-logs"),
    path("tickets/", resource_views.admin_tickets_list, name="admin-tickets"),
    path(
        "tickets/attachments/<int:attachment_id>/",
        resource_views.admin_support_ticket_attachment,
        name="admin-support-ticket-attachment",
    ),
    path(
        "tickets/<str:ticket_number>/messages/",
        resource_views.admin_ticket_messages,
        name="admin-ticket-messages",
    ),
    path(
        "tickets/<str:ticket_number>/",
        resource_views.admin_ticket_detail,
        name="admin-ticket-detail",
    ),
    path("flagged/<int:pk>/", resource_views.admin_flagged_activity_detail_write, name="admin-flagged-write"),
    path("flagged/", resource_views.admin_flagged_activities_list, name="admin-flagged"),
    path("shipping-methods/create/", resource_views.admin_shipping_method_create, name="admin-shipping-methods-create"),
    path(
        "shipping-methods/<int:pk>/",
        resource_views.admin_shipping_method_detail_write,
        name="admin-shipping-methods-write",
    ),
    path("shipping-methods/", resource_views.admin_shipping_methods_list, name="admin-shipping-methods"),
    path("shipping-zones/create/", resource_views.admin_shipping_zone_create, name="admin-shipping-zones-create"),
    path("shipping-zones/<int:pk>/", resource_views.admin_shipping_zone_detail_write, name="admin-shipping-zones-write"),
    path("shipping-zones/", resource_views.admin_shipping_zones_list, name="admin-shipping-zones"),
    path("weight-rules/create/", resource_views.admin_weight_rule_create, name="admin-weight-rules-create"),
    path("weight-rules/<int:pk>/", resource_views.admin_weight_rule_detail_write, name="admin-weight-rules-write"),
    path("weight-rules/", resource_views.admin_weight_rules_list, name="admin-weight-rules"),
    path("shipping-settings/", resource_views.admin_shipping_settings_singleton, name="admin-shipping-settings"),
    path("shipping/calculate/", resource_views.admin_shipping_calculate, name="admin-shipping-calculate"),
    path("roles/create/", resource_views.admin_role_create, name="admin-roles-create"),
    path("roles/<int:pk>/", resource_views.admin_role_detail_write, name="admin-roles-write"),
    path("roles/", resource_views.admin_roles_list, name="admin-roles"),
    path(
        "account-portal-catalog/",
        resource_views.admin_account_portal_catalog,
        name="admin-account-portal-catalog",
    ),
    path("employees/create/", resource_views.admin_employee_create, name="admin-employees-create"),
    path("employees/<int:pk>/", resource_views.admin_employee_detail_write, name="admin-employees-write"),
    path("employees/", resource_views.admin_employees_list, name="admin-employees"),
    path("security-settings/", resource_views.admin_security_settings_singleton, name="admin-security-settings"),
    path("security/summary/", resource_views.admin_security_summary, name="admin-security-summary"),
    path("site-settings/", resource_views.admin_site_settings_singleton, name="admin-site-settings"),
    path(
        "payment-gateways/<str:gateway>/",
        resource_views.admin_payment_gateway_write,
        name="admin-payment-gateway-write",
    ),
    path("payment-gateways/", resource_views.admin_payment_gateways_list, name="admin-payment-gateways"),
    path(
        "system/cleanup-modules/",
        system_cleanup_views.admin_cleanup_modules_list,
        name="admin-cleanup-modules",
    ),
    path(
        "system/cleanup/",
        system_cleanup_views.admin_cleanup_execute,
        name="admin-cleanup-execute",
    ),
    path("system/db-stats/", resource_views.admin_db_table_stats, name="admin-db-table-stats"),
]

