"""
Django settings for khudrapasal project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import json
import os

from dotenv import dotenv_values, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Primary env file for this Django project (see server/.env.example).
_ENV_PATH = BASE_DIR / ".env"


def _hydrate_google_oauth_from_dotenv() -> None:
    """
    Ensure GOOGLE_OAUTH_* are populated from .env when the process env has empty placeholders.

    load_dotenv() uses override=False by default, so an empty GOOGLE_OAUTH_CLIENT_ID injected
    by an IDE, Windows service, or container would block values from server/.env.
    """
    for path in (_ENV_PATH, BASE_DIR.parent / ".env"):
        if not path.is_file():
            continue
        vals = dotenv_values(path)
        for key in (
            "GOOGLE_OAUTH_CLIENT_ID",
            "GOOGLE_OAUTH_CLIENT_SECRET",
            "GOOGLE_OAUTH_CREDENTIALS_JSON",
            "GOOGLE_ID_TOKEN_AUDIENCE",
        ):
            raw = vals.get(key)
            if raw is None:
                continue
            file_val = str(raw).strip()
            env_val = (os.environ.get(key) or "").strip()
            if file_val and not env_val:
                os.environ[key] = file_val


# Optional server/.env for GOOGLE_OAUTH_* and other secrets (see server/.env.example).
load_dotenv(_ENV_PATH)
_hydrate_google_oauth_from_dotenv()


def _hydrate_gemini_from_dotenv() -> None:
    """
    Ensure GEMINI_API_KEY (or GOOGLE_API_KEY) is visible when set in server/.env but the process env is empty.
    Same pattern as _hydrate_google_oauth_from_dotenv.
    """
    for path in (_ENV_PATH, BASE_DIR.parent / ".env"):
        if not path.is_file():
            continue
        vals = dotenv_values(path)
        for key in ("GEMINI_API_KEY", "GOOGLE_API_KEY"):
            raw = vals.get(key)
            if raw is None:
                continue
            file_val = str(raw).strip()
            env_val = (os.environ.get(key) or "").strip()
            if file_val and not env_val:
                os.environ[key] = file_val


_hydrate_gemini_from_dotenv()

# Google Gemini (sales assistant). Prefer GEMINI_API_KEY; GOOGLE_API_KEY is a common alternate name.
GEMINI_API_KEY = (os.environ.get("GEMINI_API_KEY") or "").strip() or (os.environ.get("GOOGLE_API_KEY") or "").strip()
# Model id for generativelanguage.googleapis.com v1beta (e.g. gemini-2.0-flash, gemini-3-flash-preview).
GEMINI_MODEL = (os.environ.get("GEMINI_MODEL") or "gemini-1.5-flash").strip()

# Khalti ePayment (v2) — secret stays on the server. Test/UAT keys from Khalti merchant dashboard.
KHALTI_SECRET_KEY = (os.environ.get("KHALTI_SECRET_KEY") or "").strip()
KHALTI_BASE_URL = (os.environ.get("KHALTI_BASE_URL") or "https://khalti.com/api/v2").strip().rstrip("/")


def _resolve_google_oauth_credentials() -> tuple[str, str]:
    """Prefer env; optionally load Web client id/secret from a Google credentials JSON file."""
    cid = (os.environ.get("GOOGLE_OAUTH_CLIENT_ID") or "").strip()
    sec = (os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET") or "").strip()
    if cid and sec:
        return cid, sec
    path = (os.environ.get("GOOGLE_OAUTH_CREDENTIALS_JSON") or "").strip()
    if not path:
        candidate = BASE_DIR.parent / "continue_with_google.json"
        if candidate.is_file():
            path = str(candidate)
    if not path:
        return cid, sec
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        web = data.get("web") or {}
        if not cid:
            cid = (web.get("client_id") or "").strip()
        if not sec:
            sec = (web.get("client_secret") or "").strip()
    except (OSError, json.JSONDecodeError, TypeError, AttributeError):
        pass
    return cid, sec


def _audience_from_spa_dotenv() -> str:
    """
    GIS ID tokens are minted for the Web client id (same as VITE_GOOGLE_CLIENT_ID).
    When the API process has no GOOGLE_OAUTH_CLIENT_ID (common misconfiguration), fall back
    to the SPA env file so local and simple deployments still verify tokens.
    """
    for path in (BASE_DIR.parent / "web" / ".env", BASE_DIR.parent / ".env"):
        if not path.is_file():
            continue
        vals = dotenv_values(path)
        v = (vals.get("VITE_GOOGLE_CLIENT_ID") or "").strip()
        if v:
            return v
    return ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
# Production: set DJANGO_SECRET_KEY (see server/.env.example).
SECRET_KEY = (
    os.environ.get("DJANGO_SECRET_KEY", "").strip()
    or "django-insecure-1y9yl!01-%0#$br&26om$p^xgz2p9mcj05f%5dd4sqk5ba43ps"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Production: DJANGO_DEBUG=false
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

_hosts_raw = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").strip()
ALLOWED_HOSTS = [h.strip() for h in _hosts_raw.split(",") if h.strip()] or ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'corsheaders',
]

MIDDLEWARE = [
    # Must be first: every response (including OPTIONS preflight) must pass through here for CORS headers.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.admin_audit_middleware.AdminApiAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'family_join': '60/hour',
        'otp_send': '20/minute',
        'admin_login': '30/minute',
        'wallet_hub_lookup': '120/hour',
    },
}
# SPA on another host (e.g. khudrapasal.360winx.com → API on khudrapasalserver.360winx.com) requires CORS.
# Set DJANGO_CORS_ALLOW_ALL=false in production if you want to rely only on CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = os.environ.get("DJANGO_CORS_ALLOW_ALL", "true").strip().lower() in (
    "1",
    "true",
    "yes",
    "",
)
_default_cors_origins = [
    "https://khudrapasal.360winx.com",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
_extra_cors = os.environ.get("CORS_ALLOWED_ORIGINS", "").replace(";", ",")
CORS_ALLOWED_ORIGINS = list(_default_cors_origins)
for _part in _extra_cors.split(","):
    _o = _part.strip()
    if _o and _o not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_o)
if not CORS_ALLOW_ALL_ORIGINS and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOW_ALL_ORIGINS = True
# Large multipart admin uploads — override via env on the host.
_UPLOAD_DEFAULT_BYTES = str(100 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", _UPLOAD_DEFAULT_BYTES)
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", _UPLOAD_DEFAULT_BYTES)
)
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# SPA URL after OAuth (no trailing slash). OAuth callbacks redirect here with ?token=…
# Prefer FRONTEND_URL; BASE_URL is an alias for deployments that only set one public site origin.
FRONTEND_URL = (
    os.environ.get("FRONTEND_URL", "https://khudrapasal.360winx.com").strip()
    or os.environ.get("BASE_URL", "").strip()
    or "http://localhost:8080"
)
# Relative SPA path used when OAuth `next` is omitted (must match customer home from primary_spa_redirect).
REDIRECT_AFTER_LOGIN = (os.environ.get("REDIRECT_AFTER_LOGIN", "/portal").strip() or "/portal")
_frontend_origin = FRONTEND_URL.rstrip("/")
if _frontend_origin and _frontend_origin not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(_frontend_origin)

CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)
_extra_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "").replace(";", ",")
for _part in _extra_csrf.split(","):
    _o = _part.strip()
    if _o and _o not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_o)

# Public origin of this API for OAuth redirect_uri (e.g. https://api.example.com). Defaults to request host.
OAUTH_REDIRECT_BASE = os.environ.get("OAUTH_REDIRECT_BASE", "").rstrip("/") or None

GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET = _resolve_google_oauth_credentials()
GOOGLE_ID_TOKEN_AUDIENCE = (
    (os.environ.get("GOOGLE_ID_TOKEN_AUDIENCE") or "").strip()
    or GOOGLE_OAUTH_CLIENT_ID
    or _audience_from_spa_dotenv()
)
FACEBOOK_APP_ID = os.environ.get("FACEBOOK_APP_ID", "")
FACEBOOK_APP_SECRET = os.environ.get("FACEBOOK_APP_SECRET", "")

# Admin customer document uploads (lowercase extensions, no dot)
CUSTOMER_DOCUMENT_ALLOWED_EXTENSIONS = ("pdf", "png", "jpg", "jpeg", "webp")
# Portal KYC uploads (bytes)
KYC_UPLOAD_MAX_BYTES = int(os.environ.get("KYC_UPLOAD_MAX_BYTES", str(8 * 1024 * 1024)))

# Support ticket chat attachments (per file / per message)
SUPPORT_CHAT_MAX_ATTACHMENT_BYTES = int(
    os.environ.get("SUPPORT_CHAT_MAX_ATTACHMENT_BYTES", str(25 * 1024 * 1024))
)
SUPPORT_CHAT_MAX_ATTACHMENTS_PER_MESSAGE = int(
    os.environ.get("SUPPORT_CHAT_MAX_ATTACHMENTS_PER_MESSAGE", "5")
)

ROOT_URLCONF = 'khudrapasal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'khudrapasal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
   BASE_DIR / 'static'
] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Production: reverse proxy must serve MEDIA_URL (or equivalent storage CDN) so product images load.
# Raise proxy client_max_body_size (and Django DATA_UPLOAD_MAX_MEMORY_SIZE / FILE_UPLOAD_MAX_MEMORY_SIZE)
# if large image uploads fail with 413 or empty multipart bodies.

# Custom user model
AUTH_USER_MODEL = 'core.User'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_AUTH = {
    'USE_JWT': True,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# Jazzmin admin theme (aligned with KhudraPasal web UI: teal/green accents)
JAZZMIN_SETTINGS = {
    'site_title': 'KhudraPasal Admin',
    'site_header': 'KhudraPasal',
    'site_brand': 'KhudraPasal',
    'welcome_sign': 'Welcome to KhudraPasal Admin',
    'show_sidebar': True,
    'navigation_expanded': True,
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'authtoken.Token': 'fas fa-key',
        'sites.Site': 'fas fa-globe',
        'socialaccount.SocialApp': 'fas fa-plug',
        'socialaccount.SocialAccount': 'fas fa-share-alt',
        'socialaccount.SocialToken': 'fas fa-user-lock',
        'core.User': 'fas fa-users',
        'core.Order': 'fas fa-shopping-cart',
        'core.Product': 'fas fa-box',
        'core.Vendor': 'fas fa-store',
        'core.Wallet': 'fas fa-wallet',
        'core.WalletTransaction': 'fas fa-exchange-alt',
        'core.Category': 'fas fa-sitemap',
        'core.FamilyGroup': 'fas fa-home',
        'core.FamilyWalletCategory': 'fas fa-folder',
        'core.FamilyPortalJoinLink': 'fas fa-link',
        'core.FamilyJoinRequest': 'fas fa-user-plus',
        'core.LoyaltySettings': 'fas fa-award',
        'core.SecuritySettings': 'fas fa-shield-alt',
        'core.ShippingSettings': 'fas fa-truck-loading',
        'core.ProductWishlist': 'fas fa-heart',
        'core.PurchaseOrderLine': 'fas fa-list',
        'core.Cart': 'fas fa-shopping-basket',
        'core.CartItem': 'fas fa-cart-plus',
        'core.Reel': 'fas fa-film',
        'core.ReelView': 'fas fa-eye',
        'core.ReelComment': 'fas fa-comments',
        'core.SupportTicket': 'fas fa-life-ring',
        'core.AuditLog': 'fas fa-clipboard-list',
        'core.SiteSettings': 'fas fa-cog',
        'core.WalletSettings': 'fas fa-sliders-h',
        'core.PaymentGatewaySettings': 'fas fa-credit-card',
        'core.Coupon': 'fas fa-tag',
        'core.FlashDeal': 'fas fa-bolt',
        'core.Notification': 'fas fa-bell',
        'core.Role': 'fas fa-user-shield',
    },
    'order_with_respect_to': ['core'],
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': True,
    'brand_small_text': False,
    'brand_colour': 'navbar-success',
    'accent': 'accent-teal',
    'navbar': 'navbar-dark',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-success',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': True,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'litera',
    'dark_mode_theme': 'darkly',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

# Child must have active FamilyMember(child) to use child portal APIs (login still allows role-only unless True).
CHILD_PORTAL_REQUIRE_MEMBERSHIP = os.environ.get(
    "CHILD_PORTAL_REQUIRE_MEMBERSHIP", ""
).lower() in ("1", "true", "yes")

# Optional SMTP overrides (see core.services.mail_service). Non-empty values override SiteSettings.
# KP_SMTP_HOST, KP_SMTP_PORT, KP_SMTP_USERNAME, KP_SMTP_PASSWORD, KP_SMTP_FROM_EMAIL, KP_SMTP_FROM_NAME
# Use KP_SMTP_PASSWORD for Gmail App Passwords in production instead of storing them in the database.

# Aakash SMS (see core.services.aakash_sms). Set AAKASHSMS_AUTH_TOKEN on the server; never commit it.
AAKASHSMS_AUTH_TOKEN = os.environ.get("AAKASHSMS_AUTH_TOKEN", "").strip()
AAKASHSMS_API_URL = os.environ.get(
    "AAKASHSMS_API_URL", "https://sms.aakashsms.com/sms/v3/send"
).strip()

# Firebase Admin SDK JSON for FCM server push (optional).
# Default: repo-root `firebase-service.json` (one level above `server/`).
_default_fb = BASE_DIR.parent / "firebase-service.json"
FIREBASE_CREDENTIALS_PATH = os.environ.get(
    "FIREBASE_CREDENTIALS_PATH",
    str(_default_fb),
)
# Web push VAPID public key (Firebase Console → Cloud Messaging → Web Push certificates).
# Exposed read-only via GET /api/website/firebase-messaging/ for the SPA when VITE_FIREBASE_VAPID_KEY is unset.
FIREBASE_WEB_VAPID_KEY = os.environ.get("FIREBASE_WEB_VAPID_KEY", "").strip()